name: PR Code Analysis

on:
  pull_request:
    branches: main
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analysis
        run: |
          mkdir -p ./analysis_results
          flutter analyze --no-fatal-infos > ./analysis_results/analysis_report.txt || true

      - name: Check Formatting
        run: |
          dart format . -o none --set-exit-if-changed > ./analysis_results/format_report.txt || true

      - name: Generate Summary Report
        run: |
          echo "# PR Analysis Summary" > ./analysis_results/summary.md
          echo "## Analysis Results" >> ./analysis_results/summary.md
          echo "\`\`\`" >> ./analysis_results/summary.md
          cat ./analysis_results/analysis_report.txt >> ./analysis_results/summary.md
          echo "\`\`\`" >> ./analysis_results/summary.md

          echo "## Format Check" >> ./analysis_results/summary.md
          echo "\`\`\`" >> ./analysis_results/summary.md
          cat ./analysis_results/format_report.txt >> ./analysis_results/summary.md
          echo "\`\`\`" >> ./analysis_results/summary.md

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: analysis-results
          path: |
            ./analysis_results/
          retention-days: 14
